


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "academico";


ALTER SCHEMA "academico" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "horarios";


ALTER SCHEMA "horarios" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "lab_services";


ALTER SCHEMA "lab_services" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "labs";


ALTER SCHEMA "labs" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "notas";


ALTER SCHEMA "notas" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "practicas";


ALTER SCHEMA "practicas" OWNER TO "postgres";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE SCHEMA IF NOT EXISTS "votaciones";


ALTER SCHEMA "votaciones" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "practicas"."agreement_status" AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
);


ALTER TYPE "practicas"."agreement_status" OWNER TO "postgres";


CREATE TYPE "practicas"."agreement_type" AS ENUM (
    'PRACTICE',
    'PRELOCATION',
    'BOTH'
);


ALTER TYPE "practicas"."agreement_type" OWNER TO "postgres";


CREATE TYPE "practicas"."call_status" AS ENUM (
    'OPEN',
    'CLOSED'
);


ALTER TYPE "practicas"."call_status" OWNER TO "postgres";


CREATE TYPE "practicas"."request_status" AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
);


ALTER TYPE "practicas"."request_status" OWNER TO "postgres";


CREATE TYPE "practicas"."vacancy_status" AS ENUM (
    'OPEN',
    'CLOSED'
);


ALTER TYPE "practicas"."vacancy_status" OWNER TO "postgres";


CREATE TYPE "public"."computer_status" AS ENUM (
    'AVAILABLE',
    'IN_USE',
    'BROKEN',
    'MAINTENANCE'
);


ALTER TYPE "public"."computer_status" OWNER TO "postgres";


CREATE TYPE "public"."incident_status" AS ENUM (
    'OPEN',
    'IN_PROGRESS',
    'RESOLVED',
    'CLOSED'
);


ALTER TYPE "public"."incident_status" OWNER TO "postgres";


CREATE TYPE "public"."lab_status" AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'MAINTENANCE'
);


ALTER TYPE "public"."lab_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  selected_role_id bigint;
  selected_account_type text;
begin
  selected_account_type := lower(coalesce(new.raw_user_meta_data->>'account_type', 'estudiante'));

  if selected_account_type not in ('estudiante', 'empresa') then
    selected_account_type := 'estudiante';
  end if;

  select id
  into selected_role_id
  from public.roles
  where name = selected_account_type
  limit 1;

  if selected_role_id is null then
    raise exception 'No existe el rol para account_type %', selected_account_type;
  end if;

  insert into public.profiles (
    id,
    full_name,
    account_type,
    role_id
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    selected_account_type,
    selected_role_id
  );

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "academico"."careers" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "faculty_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "academico"."careers" OWNER TO "postgres";


ALTER TABLE "academico"."careers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "academico"."careers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "academico"."faculties" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "academico"."faculties" OWNER TO "postgres";


ALTER TABLE "academico"."faculties" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "academico"."faculties_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "academico"."municipalities" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "academico"."municipalities" OWNER TO "postgres";


ALTER TABLE "academico"."municipalities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "academico"."municipalities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "academico"."professors" (
    "id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "names" "text" NOT NULL,
    "surnames" "text" NOT NULL,
    "contact_phone" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "academico"."professors" OWNER TO "postgres";


ALTER TABLE "academico"."professors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "academico"."professors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "academico"."students" (
    "id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "names" "text" NOT NULL,
    "surnames" "text" NOT NULL,
    "ci" "text" NOT NULL,
    "academic_year" integer NOT NULL,
    "career_id" bigint NOT NULL,
    "municipality_id" bigint NOT NULL,
    "study_mode" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_brigada" bigint,
    CONSTRAINT "students_study_mode_check" CHECK (("study_mode" = ANY (ARRAY['REGULAR_DIURNO'::"text", 'CURSO_POR_ENCUENTRO'::"text"])))
);


ALTER TABLE "academico"."students" OWNER TO "postgres";


ALTER TABLE "academico"."students" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "academico"."students_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "horarios"."asignatura" (
    "id" bigint NOT NULL,
    "codigo" "text" NOT NULL,
    "nombre" "text" NOT NULL,
    "descripcion" "text",
    "año_academico" integer NOT NULL,
    "periodo" integer NOT NULL,
    "horas_presenciales" integer DEFAULT 0,
    "horas_no_presenciales" integer DEFAULT 0,
    "horas_totales" integer DEFAULT 0,
    "tipo_evaluacion" "text" DEFAULT 'EF'::"text",
    "color" "text" DEFAULT '#3498db'::"text",
    "profesor_id" bigint,
    "fecha_creacion" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "horarios"."asignatura" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "horarios"."asignatura_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "horarios"."asignatura_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "horarios"."asignatura_id_seq" OWNED BY "horarios"."asignatura"."id";



CREATE TABLE IF NOT EXISTS "horarios"."horario_general" (
    "id" bigint NOT NULL,
    "titulo" "text" DEFAULT 'Horario Docente'::"text" NOT NULL,
    "año_academico" "text" NOT NULL,
    "semestre" integer NOT NULL,
    "año_carrera" integer NOT NULL,
    "carrera" "text" DEFAULT 'INGENIERÍA INFORMÁTICA'::"text",
    "modalidad" "text" DEFAULT 'Diurno'::"text",
    "semanas_totales" integer DEFAULT 22,
    "semanas_clases" integer DEFAULT 19,
    "semanas_examenes" integer DEFAULT 3,
    "fecha_inicio" "date" NOT NULL,
    "fecha_fin" "date" NOT NULL,
    "creado_por" "uuid",
    "creado_en" timestamp with time zone DEFAULT "now"(),
    "actualizado_en" timestamp with time zone,
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "horarios"."horario_general" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "horarios"."horario_general_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "horarios"."horario_general_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "horarios"."horario_general_id_seq" OWNED BY "horarios"."horario_general"."id";



CREATE TABLE IF NOT EXISTS "horarios"."horario_semanal" (
    "id" bigint NOT NULL,
    "horario_general_id" bigint NOT NULL,
    "semana_numero" integer NOT NULL,
    "dia_semana" integer NOT NULL,
    "turno_id" bigint NOT NULL,
    "asignatura_id" bigint,
    "profesor_id" bigint,
    "color" "text",
    "es_examen" boolean DEFAULT false NOT NULL,
    "fecha_especifica" "date"
);


ALTER TABLE "horarios"."horario_semanal" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "horarios"."horario_semanal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "horarios"."horario_semanal_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "horarios"."horario_semanal_id_seq" OWNED BY "horarios"."horario_semanal"."id";



CREATE TABLE IF NOT EXISTS "horarios"."profesor" (
    "id" bigint NOT NULL,
    "codigo" "text" NOT NULL,
    "nombres" "text" NOT NULL,
    "apellidos" "text" NOT NULL,
    "categoria_academica" "text",
    "categoria_cientifica" "text",
    "email" "text",
    "telefono" "text",
    "activo" boolean DEFAULT true NOT NULL,
    "fecha_creacion" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "horarios"."profesor" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "horarios"."profesor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "horarios"."profesor_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "horarios"."profesor_id_seq" OWNED BY "horarios"."profesor"."id";



CREATE TABLE IF NOT EXISTS "horarios"."turno" (
    "id" bigint NOT NULL,
    "nombre" "text" NOT NULL,
    "hora_inicio" "text" NOT NULL,
    "hora_fin" "text" NOT NULL,
    "duracion_minutos" integer DEFAULT 90,
    "seccion" "text" NOT NULL,
    "orden" integer NOT NULL,
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "horarios"."turno" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "horarios"."turno_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "horarios"."turno_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "horarios"."turno_id_seq" OWNED BY "horarios"."turno"."id";



CREATE TABLE IF NOT EXISTS "lab_services"."computer" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "lab_id" "uuid" NOT NULL,
    "serial_number" "text" NOT NULL,
    "status" "text" DEFAULT 'AVAILABLE'::"text" NOT NULL,
    "brand" "text",
    "model" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "computer_status_check" CHECK (("status" = ANY (ARRAY['AVAILABLE'::"text", 'IN_USE'::"text", 'BROKEN'::"text", 'MAINTENANCE'::"text"])))
);


ALTER TABLE "lab_services"."computer" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "lab_services"."computers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "lab_id" "uuid" NOT NULL,
    "serial_number" "text" NOT NULL,
    "brand" "text",
    "model" "text",
    "status" "public"."computer_status" DEFAULT 'AVAILABLE'::"public"."computer_status",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "lab_services"."computers" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "lab_services"."incident" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "computer_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "status" "text" DEFAULT 'OPEN'::"text" NOT NULL,
    "reported_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "incident_status_check" CHECK (("status" = ANY (ARRAY['OPEN'::"text", 'IN_PROGRESS'::"text", 'RESOLVED'::"text", 'CLOSED'::"text"])))
);


ALTER TABLE "lab_services"."incident" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "lab_services"."incidents" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "computer_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "status" "public"."incident_status" DEFAULT 'OPEN'::"public"."incident_status",
    "reported_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "lab_services"."incidents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "lab_services"."lab" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "location" "text" NOT NULL,
    "capacity" integer DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'ACTIVE'::"text" NOT NULL,
    "technician_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "lab_status_check" CHECK (("status" = ANY (ARRAY['ACTIVE'::"text", 'INACTIVE'::"text", 'MAINTENANCE'::"text"])))
);


ALTER TABLE "lab_services"."lab" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "lab_services"."labs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "location" "text" NOT NULL,
    "capacity" integer NOT NULL,
    "status" "public"."lab_status" DEFAULT 'ACTIVE'::"public"."lab_status",
    "technician_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "lab_services"."labs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "notas"."asignatura" (
    "id_asignatura" bigint NOT NULL,
    "nombre_asignatura" "text" NOT NULL
);


ALTER TABLE "notas"."asignatura" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "notas"."asignatura_id_asignatura_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "notas"."asignatura_id_asignatura_seq" OWNER TO "postgres";


ALTER SEQUENCE "notas"."asignatura_id_asignatura_seq" OWNED BY "notas"."asignatura"."id_asignatura";



CREATE TABLE IF NOT EXISTS "notas"."brigada" (
    "id_brigada" bigint NOT NULL,
    "id_carrera" bigint NOT NULL,
    "nombre_brigada" "text" NOT NULL,
    "año_brigada" integer NOT NULL,
    "año_final_brigada" integer NOT NULL
);


ALTER TABLE "notas"."brigada" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "notas"."brigada_id_brigada_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "notas"."brigada_id_brigada_seq" OWNER TO "postgres";


ALTER SEQUENCE "notas"."brigada_id_brigada_seq" OWNED BY "notas"."brigada"."id_brigada";



CREATE TABLE IF NOT EXISTS "notas"."carrera_asignatura" (
    "id_carrera" bigint NOT NULL,
    "id_asignatura" bigint NOT NULL
);


ALTER TABLE "notas"."carrera_asignatura" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "notas"."nota" (
    "id_nota" bigint NOT NULL,
    "id_estudiante" bigint NOT NULL,
    "id_asignatura" bigint NOT NULL,
    "valor" numeric(4,2) NOT NULL,
    "año" integer NOT NULL,
    CONSTRAINT "nota_valor_check" CHECK ((("valor" >= (0)::numeric) AND ("valor" <= (100)::numeric)))
);


ALTER TABLE "notas"."nota" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "notas"."nota_id_nota_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "notas"."nota_id_nota_seq" OWNER TO "postgres";


ALTER SEQUENCE "notas"."nota_id_nota_seq" OWNED BY "notas"."nota"."id_nota";



CREATE TABLE IF NOT EXISTS "practicas"."agreement" (
    "id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "type" "practicas"."agreement_type" NOT NULL,
    "status" "practicas"."agreement_status" DEFAULT 'PENDING'::"practicas"."agreement_status" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "specialty" "text" NOT NULL,
    "students_needed" integer NOT NULL,
    "bank_problem_document" "text",
    "approved_by_practices" boolean DEFAULT false NOT NULL,
    "approved_by_prelocation" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."agreement" OWNER TO "postgres";


ALTER TABLE "practicas"."agreement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."agreement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."company" (
    "id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "phone" "text",
    "address" "text",
    "municipality_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."company" OWNER TO "postgres";


ALTER TABLE "practicas"."company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."prelocalization_assignment" (
    "id" bigint NOT NULL,
    "prelocalization_call_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "vacancy_id" bigint NOT NULL,
    "academic_year" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."prelocalization_assignment" OWNER TO "postgres";


ALTER TABLE "practicas"."prelocalization_assignment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."prelocalization_assignment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."prelocalization_call" (
    "id" bigint NOT NULL,
    "career_id" bigint NOT NULL,
    "academic_year" integer NOT NULL,
    "status" "practicas"."call_status" DEFAULT 'OPEN'::"practicas"."call_status" NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."prelocalization_call" OWNER TO "postgres";


ALTER TABLE "practicas"."prelocalization_call" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."prelocalization_call_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."prelocalization_ranking" (
    "id" bigint NOT NULL,
    "prelocalization_call_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "position" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."prelocalization_ranking" OWNER TO "postgres";


ALTER TABLE "practicas"."prelocalization_ranking" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."prelocalization_ranking_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."request" (
    "id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "vacancy_id" bigint NOT NULL,
    "status" "practicas"."request_status" DEFAULT 'PENDING'::"practicas"."request_status" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."request" OWNER TO "postgres";


ALTER TABLE "practicas"."request" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."request_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "practicas"."vacancy" (
    "id" bigint NOT NULL,
    "agreement_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "specialty" "text" NOT NULL,
    "slots" integer NOT NULL,
    "status" "practicas"."vacancy_status" DEFAULT 'OPEN'::"practicas"."vacancy_status" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "practicas"."vacancy" OWNER TO "postgres";


ALTER TABLE "practicas"."vacancy" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "practicas"."vacancy_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text" NOT NULL,
    "role_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_type" "text" NOT NULL,
    CONSTRAINT "profiles_account_type_check" CHECK (("account_type" = ANY (ARRAY['estudiante'::"text", 'empresa'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "votaciones"."candidato" (
    "id" bigint NOT NULL,
    "nombre" "text" NOT NULL,
    "descripcion" "text",
    "foto" "text",
    "tipo" "text" NOT NULL,
    "estudiante_id" bigint,
    "profile_id" "uuid",
    CONSTRAINT "candidato_tipo_check" CHECK (("tipo" = ANY (ARRAY['organizacion'::"text", 'lider'::"text", 'ambos'::"text"])))
);


ALTER TABLE "votaciones"."candidato" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "votaciones"."candidato_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "votaciones"."candidato_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "votaciones"."candidato_id_seq" OWNED BY "votaciones"."candidato"."id";



CREATE TABLE IF NOT EXISTS "votaciones"."configuracion" (
    "id" integer DEFAULT 1 NOT NULL,
    "inicio_votacion" timestamp with time zone,
    "fin_votacion" timestamp with time zone
);


ALTER TABLE "votaciones"."configuracion" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "votaciones"."voto_lider" (
    "id" bigint NOT NULL,
    "usuario_id" "uuid",
    "candidato_id" bigint,
    "fecha_voto" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "votaciones"."voto_lider" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "votaciones"."voto_lider_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "votaciones"."voto_lider_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "votaciones"."voto_lider_id_seq" OWNED BY "votaciones"."voto_lider"."id";



CREATE TABLE IF NOT EXISTS "votaciones"."voto_organizacion" (
    "id" bigint NOT NULL,
    "usuario_id" "uuid",
    "candidato_id" bigint,
    "fecha_voto" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "votaciones"."voto_organizacion" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "votaciones"."voto_organizacion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "votaciones"."voto_organizacion_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "votaciones"."voto_organizacion_id_seq" OWNED BY "votaciones"."voto_organizacion"."id";



ALTER TABLE ONLY "horarios"."asignatura" ALTER COLUMN "id" SET DEFAULT "nextval"('"horarios"."asignatura_id_seq"'::"regclass");



ALTER TABLE ONLY "horarios"."horario_general" ALTER COLUMN "id" SET DEFAULT "nextval"('"horarios"."horario_general_id_seq"'::"regclass");



ALTER TABLE ONLY "horarios"."horario_semanal" ALTER COLUMN "id" SET DEFAULT "nextval"('"horarios"."horario_semanal_id_seq"'::"regclass");



ALTER TABLE ONLY "horarios"."profesor" ALTER COLUMN "id" SET DEFAULT "nextval"('"horarios"."profesor_id_seq"'::"regclass");



ALTER TABLE ONLY "horarios"."turno" ALTER COLUMN "id" SET DEFAULT "nextval"('"horarios"."turno_id_seq"'::"regclass");



ALTER TABLE ONLY "notas"."asignatura" ALTER COLUMN "id_asignatura" SET DEFAULT "nextval"('"notas"."asignatura_id_asignatura_seq"'::"regclass");



ALTER TABLE ONLY "notas"."brigada" ALTER COLUMN "id_brigada" SET DEFAULT "nextval"('"notas"."brigada_id_brigada_seq"'::"regclass");



ALTER TABLE ONLY "notas"."nota" ALTER COLUMN "id_nota" SET DEFAULT "nextval"('"notas"."nota_id_nota_seq"'::"regclass");



ALTER TABLE ONLY "votaciones"."candidato" ALTER COLUMN "id" SET DEFAULT "nextval"('"votaciones"."candidato_id_seq"'::"regclass");



ALTER TABLE ONLY "votaciones"."voto_lider" ALTER COLUMN "id" SET DEFAULT "nextval"('"votaciones"."voto_lider_id_seq"'::"regclass");



ALTER TABLE ONLY "votaciones"."voto_organizacion" ALTER COLUMN "id" SET DEFAULT "nextval"('"votaciones"."voto_organizacion_id_seq"'::"regclass");



ALTER TABLE ONLY "academico"."careers"
    ADD CONSTRAINT "careers_faculty_name_unique" UNIQUE ("faculty_id", "name");



ALTER TABLE ONLY "academico"."careers"
    ADD CONSTRAINT "careers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "academico"."faculties"
    ADD CONSTRAINT "faculties_name_key" UNIQUE ("name");



ALTER TABLE ONLY "academico"."faculties"
    ADD CONSTRAINT "faculties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "academico"."municipalities"
    ADD CONSTRAINT "municipalities_name_key" UNIQUE ("name");



ALTER TABLE ONLY "academico"."municipalities"
    ADD CONSTRAINT "municipalities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "academico"."professors"
    ADD CONSTRAINT "professors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "academico"."professors"
    ADD CONSTRAINT "professors_profile_id_key" UNIQUE ("profile_id");



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_ci_key" UNIQUE ("ci");



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_profile_id_key" UNIQUE ("profile_id");



ALTER TABLE ONLY "horarios"."asignatura"
    ADD CONSTRAINT "asignatura_codigo_key" UNIQUE ("codigo");



ALTER TABLE ONLY "horarios"."asignatura"
    ADD CONSTRAINT "asignatura_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "horarios"."horario_general"
    ADD CONSTRAINT "horario_general_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "horarios"."horario_semanal"
    ADD CONSTRAINT "horario_semanal_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "horarios"."profesor"
    ADD CONSTRAINT "profesor_codigo_key" UNIQUE ("codigo");



ALTER TABLE ONLY "horarios"."profesor"
    ADD CONSTRAINT "profesor_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "horarios"."turno"
    ADD CONSTRAINT "turno_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."computer"
    ADD CONSTRAINT "computer_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."computer"
    ADD CONSTRAINT "computer_serial_number_key" UNIQUE ("serial_number");



ALTER TABLE ONLY "lab_services"."computers"
    ADD CONSTRAINT "computers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."computers"
    ADD CONSTRAINT "computers_serial_number_key" UNIQUE ("serial_number");



ALTER TABLE ONLY "lab_services"."incident"
    ADD CONSTRAINT "incident_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."incidents"
    ADD CONSTRAINT "incidents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."lab"
    ADD CONSTRAINT "lab_name_key" UNIQUE ("name");



ALTER TABLE ONLY "lab_services"."lab"
    ADD CONSTRAINT "lab_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "lab_services"."labs"
    ADD CONSTRAINT "labs_name_key" UNIQUE ("name");



ALTER TABLE ONLY "lab_services"."labs"
    ADD CONSTRAINT "labs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "notas"."asignatura"
    ADD CONSTRAINT "asignatura_pkey" PRIMARY KEY ("id_asignatura");



ALTER TABLE ONLY "notas"."brigada"
    ADD CONSTRAINT "brigada_pkey" PRIMARY KEY ("id_brigada");



ALTER TABLE ONLY "notas"."carrera_asignatura"
    ADD CONSTRAINT "carrera_asignatura_pkey" PRIMARY KEY ("id_carrera", "id_asignatura");



ALTER TABLE ONLY "notas"."nota"
    ADD CONSTRAINT "nota_pkey" PRIMARY KEY ("id_nota");



ALTER TABLE ONLY "practicas"."agreement"
    ADD CONSTRAINT "agreement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."company"
    ADD CONSTRAINT "company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."company"
    ADD CONSTRAINT "company_profile_id_key" UNIQUE ("profile_id");



ALTER TABLE ONLY "practicas"."prelocalization_assignment"
    ADD CONSTRAINT "prelocalization_assignment_call_student_unique" UNIQUE ("prelocalization_call_id", "student_id");



ALTER TABLE ONLY "practicas"."prelocalization_assignment"
    ADD CONSTRAINT "prelocalization_assignment_call_vacancy_unique" UNIQUE ("prelocalization_call_id", "vacancy_id");



ALTER TABLE ONLY "practicas"."prelocalization_assignment"
    ADD CONSTRAINT "prelocalization_assignment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."prelocalization_call"
    ADD CONSTRAINT "prelocalization_call_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."prelocalization_ranking"
    ADD CONSTRAINT "prelocalization_ranking_call_position_unique" UNIQUE ("prelocalization_call_id", "position");



ALTER TABLE ONLY "practicas"."prelocalization_ranking"
    ADD CONSTRAINT "prelocalization_ranking_call_student_unique" UNIQUE ("prelocalization_call_id", "student_id");



ALTER TABLE ONLY "practicas"."prelocalization_ranking"
    ADD CONSTRAINT "prelocalization_ranking_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."request"
    ADD CONSTRAINT "request_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "practicas"."vacancy"
    ADD CONSTRAINT "vacancy_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "votaciones"."candidato"
    ADD CONSTRAINT "candidato_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "votaciones"."configuracion"
    ADD CONSTRAINT "configuracion_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "votaciones"."voto_lider"
    ADD CONSTRAINT "voto_lider_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "votaciones"."voto_lider"
    ADD CONSTRAINT "voto_lider_usuario_id_key" UNIQUE ("usuario_id");



ALTER TABLE ONLY "votaciones"."voto_organizacion"
    ADD CONSTRAINT "voto_organizacion_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "votaciones"."voto_organizacion"
    ADD CONSTRAINT "voto_organizacion_usuario_id_candidato_id_key" UNIQUE ("usuario_id", "candidato_id");



CREATE INDEX "idx_hs_asignatura" ON "horarios"."horario_semanal" USING "btree" ("asignatura_id");



CREATE INDEX "idx_hs_horario" ON "horarios"."horario_semanal" USING "btree" ("horario_general_id");



CREATE INDEX "idx_hs_profesor" ON "horarios"."horario_semanal" USING "btree" ("profesor_id");



CREATE INDEX "idx_hs_semana" ON "horarios"."horario_semanal" USING "btree" ("semana_numero");



ALTER TABLE ONLY "academico"."careers"
    ADD CONSTRAINT "careers_faculty_id_fkey" FOREIGN KEY ("faculty_id") REFERENCES "academico"."faculties"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "academico"."professors"
    ADD CONSTRAINT "professors_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_career_id_fkey" FOREIGN KEY ("career_id") REFERENCES "academico"."careers"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_id_brigada_fkey" FOREIGN KEY ("id_brigada") REFERENCES "notas"."brigada"("id_brigada") ON DELETE SET NULL;



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_municipality_id_fkey" FOREIGN KEY ("municipality_id") REFERENCES "academico"."municipalities"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "academico"."students"
    ADD CONSTRAINT "students_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "horarios"."asignatura"
    ADD CONSTRAINT "asignatura_profesor_id_fkey" FOREIGN KEY ("profesor_id") REFERENCES "horarios"."profesor"("id");



ALTER TABLE ONLY "horarios"."horario_general"
    ADD CONSTRAINT "horario_general_creado_por_fkey" FOREIGN KEY ("creado_por") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "horarios"."horario_semanal"
    ADD CONSTRAINT "horario_semanal_asignatura_id_fkey" FOREIGN KEY ("asignatura_id") REFERENCES "horarios"."asignatura"("id");



ALTER TABLE ONLY "horarios"."horario_semanal"
    ADD CONSTRAINT "horario_semanal_horario_general_id_fkey" FOREIGN KEY ("horario_general_id") REFERENCES "horarios"."horario_general"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "horarios"."horario_semanal"
    ADD CONSTRAINT "horario_semanal_profesor_id_fkey" FOREIGN KEY ("profesor_id") REFERENCES "horarios"."profesor"("id");



ALTER TABLE ONLY "horarios"."horario_semanal"
    ADD CONSTRAINT "horario_semanal_turno_id_fkey" FOREIGN KEY ("turno_id") REFERENCES "horarios"."turno"("id");



ALTER TABLE ONLY "lab_services"."computer"
    ADD CONSTRAINT "computer_lab_id_fkey" FOREIGN KEY ("lab_id") REFERENCES "lab_services"."lab"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "lab_services"."computers"
    ADD CONSTRAINT "computers_lab_id_fkey" FOREIGN KEY ("lab_id") REFERENCES "lab_services"."labs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "lab_services"."incident"
    ADD CONSTRAINT "incident_computer_id_fkey" FOREIGN KEY ("computer_id") REFERENCES "lab_services"."computer"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "lab_services"."incident"
    ADD CONSTRAINT "incident_reported_by_fkey" FOREIGN KEY ("reported_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "lab_services"."incidents"
    ADD CONSTRAINT "incidents_computer_id_fkey" FOREIGN KEY ("computer_id") REFERENCES "lab_services"."computers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "lab_services"."lab"
    ADD CONSTRAINT "lab_technician_id_fkey" FOREIGN KEY ("technician_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "notas"."carrera_asignatura"
    ADD CONSTRAINT "carrera_asignatura_id_asignatura_fkey" FOREIGN KEY ("id_asignatura") REFERENCES "notas"."asignatura"("id_asignatura") ON DELETE CASCADE;



ALTER TABLE ONLY "notas"."nota"
    ADD CONSTRAINT "nota_id_asignatura_fkey" FOREIGN KEY ("id_asignatura") REFERENCES "notas"."asignatura"("id_asignatura");



ALTER TABLE ONLY "practicas"."agreement"
    ADD CONSTRAINT "agreement_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "practicas"."company"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "practicas"."company"
    ADD CONSTRAINT "company_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "practicas"."prelocalization_assignment"
    ADD CONSTRAINT "prelocalization_assignment_prelocalization_call_id_fkey" FOREIGN KEY ("prelocalization_call_id") REFERENCES "practicas"."prelocalization_call"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "practicas"."prelocalization_assignment"
    ADD CONSTRAINT "prelocalization_assignment_vacancy_id_fkey" FOREIGN KEY ("vacancy_id") REFERENCES "practicas"."vacancy"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "practicas"."prelocalization_call"
    ADD CONSTRAINT "prelocalization_call_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "practicas"."prelocalization_ranking"
    ADD CONSTRAINT "prelocalization_ranking_prelocalization_call_id_fkey" FOREIGN KEY ("prelocalization_call_id") REFERENCES "practicas"."prelocalization_call"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "practicas"."request"
    ADD CONSTRAINT "request_vacancy_id_fkey" FOREIGN KEY ("vacancy_id") REFERENCES "practicas"."vacancy"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "practicas"."vacancy"
    ADD CONSTRAINT "vacancy_agreement_id_fkey" FOREIGN KEY ("agreement_id") REFERENCES "practicas"."agreement"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "votaciones"."candidato"
    ADD CONSTRAINT "candidato_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES "academico"."students"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "votaciones"."candidato"
    ADD CONSTRAINT "candidato_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "votaciones"."voto_lider"
    ADD CONSTRAINT "voto_lider_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "votaciones"."candidato"("id");



ALTER TABLE ONLY "votaciones"."voto_lider"
    ADD CONSTRAINT "voto_lider_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "votaciones"."voto_organizacion"
    ADD CONSTRAINT "voto_organizacion_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "votaciones"."candidato"("id");



ALTER TABLE ONLY "votaciones"."voto_organizacion"
    ADD CONSTRAINT "voto_organizacion_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "auth"."users"("id");



CREATE POLICY "allow_all" ON "horarios"."asignatura" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "horarios"."horario_general" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "horarios"."horario_semanal" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "horarios"."profesor" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "horarios"."turno" TO "authenticated", "anon" USING (true) WITH CHECK (true);



ALTER TABLE "horarios"."asignatura" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "horarios"."horario_general" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "horarios"."horario_semanal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "horarios"."profesor" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "horarios"."turno" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "admin_computers_all" ON "lab_services"."computers" TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'lab_admin'::"text"));



CREATE POLICY "admin_incidents_all" ON "lab_services"."incidents" TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'lab_admin'::"text"));



CREATE POLICY "admin_labs_all" ON "lab_services"."labs" TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'lab_admin'::"text"));



CREATE POLICY "allow_all" ON "lab_services"."computer" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "lab_services"."incident" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "lab_services"."lab" TO "authenticated", "anon" USING (true) WITH CHECK (true);



ALTER TABLE "lab_services"."computer" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "lab_services"."computers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "lab_services"."incident" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "lab_services"."incidents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "lab_services"."lab" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "lab_services"."labs" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "technician_incident_control" ON "lab_services"."incidents" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("lab_services"."computers"
     JOIN "lab_services"."labs" ON (("labs"."id" = "computers"."lab_id")))
  WHERE (("computers"."id" = "incidents"."computer_id") AND ("labs"."technician_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM ("lab_services"."computers"
     JOIN "lab_services"."labs" ON (("labs"."id" = "computers"."lab_id")))
  WHERE (("computers"."id" = "incidents"."computer_id") AND ("labs"."technician_id" = "auth"."uid"())))));



CREATE POLICY "technician_read_own_computers" ON "lab_services"."computers" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "lab_services"."labs"
  WHERE (("labs"."id" = "computers"."lab_id") AND ("labs"."technician_id" = "auth"."uid"())))));



CREATE POLICY "technician_read_own_labs" ON "lab_services"."labs" FOR SELECT TO "authenticated" USING (("technician_id" = "auth"."uid"()));



CREATE POLICY "allow_all" ON "notas"."asignatura" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "notas"."brigada" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "notas"."carrera_asignatura" TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_all" ON "notas"."nota" TO "authenticated", "anon" USING (true) WITH CHECK (true);



ALTER TABLE "notas"."asignatura" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "notas"."brigada" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "notas"."carrera_asignatura" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "notas"."nota" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Authenticated users can read roles" ON "public"."roles" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can read their own profile" ON "public"."profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can update their own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id"));



CREATE POLICY "allow_read_profiles" ON "public"."profiles" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "allow_read_roles" ON "public"."roles" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "votaciones"."candidato" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "votaciones"."configuracion" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "votaciones"."voto_lider" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "votaciones"."voto_organizacion" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "academico" TO "service_role";



GRANT USAGE ON SCHEMA "horarios" TO "anon";
GRANT USAGE ON SCHEMA "horarios" TO "authenticated";



GRANT USAGE ON SCHEMA "lab_services" TO "service_role";



GRANT USAGE ON SCHEMA "labs" TO "anon";
GRANT USAGE ON SCHEMA "labs" TO "authenticated";
GRANT USAGE ON SCHEMA "labs" TO "service_role";



GRANT USAGE ON SCHEMA "notas" TO "service_role";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT USAGE ON SCHEMA "votaciones" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";












GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."careers" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."careers" TO "authenticated";
GRANT ALL ON TABLE "academico"."careers" TO "service_role";



GRANT ALL ON SEQUENCE "academico"."careers_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."faculties" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."faculties" TO "authenticated";
GRANT ALL ON TABLE "academico"."faculties" TO "service_role";



GRANT ALL ON SEQUENCE "academico"."faculties_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."municipalities" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."municipalities" TO "authenticated";
GRANT ALL ON TABLE "academico"."municipalities" TO "service_role";



GRANT ALL ON SEQUENCE "academico"."municipalities_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."professors" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."professors" TO "authenticated";
GRANT ALL ON TABLE "academico"."professors" TO "service_role";



GRANT ALL ON SEQUENCE "academico"."professors_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."students" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "academico"."students" TO "authenticated";
GRANT ALL ON TABLE "academico"."students" TO "service_role";



GRANT ALL ON SEQUENCE "academico"."students_id_seq" TO "service_role";









GRANT ALL ON TABLE "horarios"."asignatura" TO "anon";
GRANT ALL ON TABLE "horarios"."asignatura" TO "authenticated";
GRANT ALL ON TABLE "horarios"."asignatura" TO "service_role";



GRANT ALL ON SEQUENCE "horarios"."asignatura_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "horarios"."asignatura_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "horarios"."asignatura_id_seq" TO "service_role";



GRANT ALL ON TABLE "horarios"."horario_general" TO "anon";
GRANT ALL ON TABLE "horarios"."horario_general" TO "authenticated";
GRANT ALL ON TABLE "horarios"."horario_general" TO "service_role";



GRANT ALL ON SEQUENCE "horarios"."horario_general_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "horarios"."horario_general_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "horarios"."horario_general_id_seq" TO "service_role";



GRANT ALL ON TABLE "horarios"."horario_semanal" TO "anon";
GRANT ALL ON TABLE "horarios"."horario_semanal" TO "authenticated";
GRANT ALL ON TABLE "horarios"."horario_semanal" TO "service_role";



GRANT ALL ON SEQUENCE "horarios"."horario_semanal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "horarios"."horario_semanal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "horarios"."horario_semanal_id_seq" TO "service_role";



GRANT ALL ON TABLE "horarios"."profesor" TO "anon";
GRANT ALL ON TABLE "horarios"."profesor" TO "authenticated";
GRANT ALL ON TABLE "horarios"."profesor" TO "service_role";



GRANT ALL ON SEQUENCE "horarios"."profesor_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "horarios"."profesor_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "horarios"."profesor_id_seq" TO "service_role";



GRANT ALL ON TABLE "horarios"."turno" TO "anon";
GRANT ALL ON TABLE "horarios"."turno" TO "authenticated";
GRANT ALL ON TABLE "horarios"."turno" TO "service_role";



GRANT ALL ON SEQUENCE "horarios"."turno_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "horarios"."turno_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "horarios"."turno_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."computer" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."computer" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."computer" TO "service_role";



GRANT ALL ON TABLE "lab_services"."computers" TO "anon";
GRANT ALL ON TABLE "lab_services"."computers" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."computers" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."incident" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."incident" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."incident" TO "service_role";



GRANT ALL ON TABLE "lab_services"."incidents" TO "anon";
GRANT ALL ON TABLE "lab_services"."incidents" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."incidents" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."lab" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "lab_services"."lab" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."lab" TO "service_role";



GRANT ALL ON TABLE "lab_services"."labs" TO "anon";
GRANT ALL ON TABLE "lab_services"."labs" TO "authenticated";
GRANT ALL ON TABLE "lab_services"."labs" TO "service_role";



GRANT ALL ON TABLE "notas"."asignatura" TO "service_role";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."asignatura" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."asignatura" TO "authenticated";



GRANT ALL ON SEQUENCE "notas"."asignatura_id_asignatura_seq" TO "service_role";



GRANT ALL ON TABLE "notas"."brigada" TO "service_role";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."brigada" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."brigada" TO "authenticated";



GRANT ALL ON SEQUENCE "notas"."brigada_id_brigada_seq" TO "service_role";



GRANT ALL ON TABLE "notas"."carrera_asignatura" TO "service_role";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."carrera_asignatura" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."carrera_asignatura" TO "authenticated";



GRANT ALL ON TABLE "notas"."nota" TO "service_role";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."nota" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "notas"."nota" TO "authenticated";



GRANT ALL ON SEQUENCE "notas"."nota_id_nota_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."agreement" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."agreement" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."agreement" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."company" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."company" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."company" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_assignment" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_assignment" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_assignment" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_call" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_call" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_call" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_ranking" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_ranking" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."prelocalization_ranking" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."request" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."request" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."request" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."vacancy" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."vacancy" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "practicas"."vacancy" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";









GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."candidato" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."candidato" TO "authenticated";
GRANT ALL ON TABLE "votaciones"."candidato" TO "service_role";



GRANT ALL ON SEQUENCE "votaciones"."candidato_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."configuracion" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."configuracion" TO "authenticated";
GRANT ALL ON TABLE "votaciones"."configuracion" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."voto_lider" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."voto_lider" TO "authenticated";
GRANT ALL ON TABLE "votaciones"."voto_lider" TO "service_role";



GRANT ALL ON SEQUENCE "votaciones"."voto_lider_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."voto_organizacion" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "votaciones"."voto_organizacion" TO "authenticated";
GRANT ALL ON TABLE "votaciones"."voto_organizacion" TO "service_role";



GRANT ALL ON SEQUENCE "votaciones"."voto_organizacion_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "labs" GRANT ALL ON SEQUENCES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "labs" GRANT ALL ON TABLES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "allow_all" on "horarios"."asignatura";

drop policy "allow_all" on "horarios"."horario_general";

drop policy "allow_all" on "horarios"."horario_semanal";

drop policy "allow_all" on "horarios"."profesor";

drop policy "allow_all" on "horarios"."turno";

drop policy "allow_all" on "lab_services"."computer";

drop policy "allow_all" on "lab_services"."incident";

drop policy "allow_all" on "lab_services"."lab";

drop policy "allow_all" on "notas"."asignatura";

drop policy "allow_all" on "notas"."brigada";

drop policy "allow_all" on "notas"."carrera_asignatura";

drop policy "allow_all" on "notas"."nota";

drop policy "allow_read_profiles" on "public"."profiles";

drop policy "allow_read_roles" on "public"."roles";

alter table "academico"."professors" drop constraint "professors_profile_id_fkey";

alter table "academico"."students" drop constraint "students_profile_id_fkey";

alter table "practicas"."company" drop constraint "company_profile_id_fkey";

alter table "practicas"."prelocalization_call" drop constraint "prelocalization_call_created_by_fkey";

alter table "public"."profiles" drop constraint "profiles_role_id_fkey";

alter table "votaciones"."candidato" drop constraint "candidato_profile_id_fkey";

alter table "lab_services"."computers" alter column "status" set default 'AVAILABLE'::public.computer_status;

alter table "lab_services"."computers" alter column "status" set data type public.computer_status using "status"::text::public.computer_status;

alter table "lab_services"."incidents" alter column "status" set default 'OPEN'::public.incident_status;

alter table "lab_services"."incidents" alter column "status" set data type public.incident_status using "status"::text::public.incident_status;

alter table "lab_services"."labs" alter column "status" set default 'ACTIVE'::public.lab_status;

alter table "lab_services"."labs" alter column "status" set data type public.lab_status using "status"::text::public.lab_status;

alter table "academico"."professors" add constraint "professors_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "academico"."professors" validate constraint "professors_profile_id_fkey";

alter table "academico"."students" add constraint "students_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "academico"."students" validate constraint "students_profile_id_fkey";

alter table "practicas"."company" add constraint "company_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."company" validate constraint "company_profile_id_fkey";

alter table "practicas"."prelocalization_call" add constraint "prelocalization_call_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "practicas"."prelocalization_call" validate constraint "prelocalization_call_created_by_fkey";

alter table "public"."profiles" add constraint "profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."profiles" validate constraint "profiles_role_id_fkey";

alter table "votaciones"."candidato" add constraint "candidato_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "votaciones"."candidato" validate constraint "candidato_profile_id_fkey";


  create policy "allow_all"
  on "horarios"."asignatura"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."horario_general"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."horario_semanal"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."profesor"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."turno"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "lab_services"."computer"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "lab_services"."incident"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "lab_services"."lab"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "notas"."asignatura"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "notas"."brigada"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "notas"."carrera_asignatura"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "notas"."nota"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_read_profiles"
  on "public"."profiles"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "allow_read_roles"
  on "public"."roles"
  as permissive
  for select
  to anon, authenticated
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


