drop extension if exists "pg_net";

create schema if not exists "academico";

create schema if not exists "horarios";

create schema if not exists "lab_services";

create schema if not exists "practicas";

create type "practicas"."agreement_status" as enum ('PENDING', 'APPROVED', 'REJECTED');

create type "practicas"."agreement_type" as enum ('PRACTICE', 'PRELOCATION', 'BOTH');

create type "practicas"."call_status" as enum ('OPEN', 'CLOSED');

create type "practicas"."request_status" as enum ('PENDING', 'APPROVED', 'REJECTED');

create type "practicas"."vacancy_status" as enum ('OPEN', 'CLOSED');

create type "public"."computer_status" as enum ('AVAILABLE', 'IN_USE', 'BROKEN', 'MAINTENANCE');

create type "public"."incident_status" as enum ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');

create type "public"."lab_status" as enum ('ACTIVE', 'INACTIVE', 'MAINTENANCE');

create sequence "horarios"."asignatura_id_seq";

create sequence "horarios"."horario_general_id_seq";

create sequence "horarios"."horario_semanal_id_seq";

create sequence "horarios"."profesor_id_seq";

create sequence "horarios"."turno_id_seq";


  create table "academico"."careers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "faculty_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "academico"."faculties" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "academico"."municipalities" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "academico"."professors" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid not null,
    "names" text not null,
    "surnames" text not null,
    "contact_phone" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "academico"."students" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid not null,
    "names" text not null,
    "surnames" text not null,
    "ci" text not null,
    "academic_year" integer not null,
    "career_id" bigint not null,
    "municipality_id" bigint not null,
    "study_mode" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "horarios"."asignatura" (
    "id" bigint not null default nextval('horarios.asignatura_id_seq'::regclass),
    "codigo" text not null,
    "nombre" text not null,
    "descripcion" text,
    "año_academico" integer not null,
    "periodo" integer not null,
    "horas_presenciales" integer default 0,
    "horas_no_presenciales" integer default 0,
    "horas_totales" integer default 0,
    "tipo_evaluacion" text default 'EF'::text,
    "color" text default '#3498db'::text,
    "profesor_id" bigint,
    "fecha_creacion" timestamp with time zone default now()
      );


alter table "horarios"."asignatura" enable row level security;


  create table "horarios"."horario_general" (
    "id" bigint not null default nextval('horarios.horario_general_id_seq'::regclass),
    "titulo" text not null default 'Horario Docente'::text,
    "año_academico" text not null,
    "semestre" integer not null,
    "año_carrera" integer not null,
    "carrera" text default 'INGENIERÍA INFORMÁTICA'::text,
    "modalidad" text default 'Diurno'::text,
    "semanas_totales" integer default 22,
    "semanas_clases" integer default 19,
    "semanas_examenes" integer default 3,
    "fecha_inicio" date not null,
    "fecha_fin" date not null,
    "creado_por" uuid,
    "creado_en" timestamp with time zone default now(),
    "actualizado_en" timestamp with time zone,
    "activo" boolean not null default true
      );


alter table "horarios"."horario_general" enable row level security;


  create table "horarios"."horario_semanal" (
    "id" bigint not null default nextval('horarios.horario_semanal_id_seq'::regclass),
    "horario_general_id" bigint not null,
    "semana_numero" integer not null,
    "dia_semana" integer not null,
    "turno_id" bigint not null,
    "asignatura_id" bigint,
    "profesor_id" bigint,
    "color" text,
    "es_examen" boolean not null default false,
    "fecha_especifica" date
      );


alter table "horarios"."horario_semanal" enable row level security;


  create table "horarios"."profesor" (
    "id" bigint not null default nextval('horarios.profesor_id_seq'::regclass),
    "codigo" text not null,
    "nombres" text not null,
    "apellidos" text not null,
    "categoria_academica" text,
    "categoria_cientifica" text,
    "email" text,
    "telefono" text,
    "activo" boolean not null default true,
    "fecha_creacion" timestamp with time zone default now()
      );


alter table "horarios"."profesor" enable row level security;


  create table "horarios"."turno" (
    "id" bigint not null default nextval('horarios.turno_id_seq'::regclass),
    "nombre" text not null,
    "hora_inicio" text not null,
    "hora_fin" text not null,
    "duracion_minutos" integer default 90,
    "seccion" text not null,
    "orden" integer not null,
    "activo" boolean not null default true
      );


alter table "horarios"."turno" enable row level security;


  create table "lab_services"."computers" (
    "id" uuid not null default gen_random_uuid(),
    "lab_id" uuid not null,
    "serial_number" text not null,
    "brand" text,
    "model" text,
    "status" public.computer_status default 'AVAILABLE'::public.computer_status,
    "created_at" timestamp with time zone default now()
      );


alter table "lab_services"."computers" enable row level security;


  create table "lab_services"."incidents" (
    "id" uuid not null default gen_random_uuid(),
    "computer_id" uuid not null,
    "title" text not null,
    "description" text not null,
    "status" public.incident_status default 'OPEN'::public.incident_status,
    "reported_by" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "lab_services"."incidents" enable row level security;


  create table "lab_services"."labs" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "location" text not null,
    "capacity" integer not null,
    "status" public.lab_status default 'ACTIVE'::public.lab_status,
    "technician_id" uuid,
    "created_at" timestamp with time zone default now()
      );


alter table "lab_services"."labs" enable row level security;


  create table "practicas"."agreement" (
    "id" bigint generated by default as identity not null,
    "company_id" bigint not null,
    "type" practicas.agreement_type not null,
    "status" practicas.agreement_status not null default 'PENDING'::practicas.agreement_status,
    "title" text not null,
    "description" text not null,
    "specialty" text not null,
    "students_needed" integer not null,
    "bank_problem_document" text,
    "approved_by_practices" boolean not null default false,
    "approved_by_prelocation" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."company" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid not null,
    "name" text not null,
    "phone" text,
    "address" text,
    "municipality_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."prelocalization_assignment" (
    "id" bigint generated by default as identity not null,
    "prelocalization_call_id" bigint not null,
    "student_id" bigint not null,
    "vacancy_id" bigint not null,
    "academic_year" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."prelocalization_call" (
    "id" bigint generated by default as identity not null,
    "career_id" bigint not null,
    "academic_year" integer not null,
    "status" practicas.call_status not null default 'OPEN'::practicas.call_status,
    "created_by" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."prelocalization_ranking" (
    "id" bigint generated by default as identity not null,
    "prelocalization_call_id" bigint not null,
    "student_id" bigint not null,
    "position" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."request" (
    "id" bigint generated by default as identity not null,
    "student_id" bigint not null,
    "vacancy_id" bigint not null,
    "status" practicas.request_status not null default 'PENDING'::practicas.request_status,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "practicas"."vacancy" (
    "id" bigint generated by default as identity not null,
    "agreement_id" bigint not null,
    "title" text not null,
    "specialty" text not null,
    "slots" integer not null,
    "status" practicas.vacancy_status not null default 'OPEN'::practicas.vacancy_status,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text not null,
    "role_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "account_type" text not null
      );


alter table "public"."profiles" enable row level security;


  create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."roles" enable row level security;

alter sequence "horarios"."asignatura_id_seq" owned by "horarios"."asignatura"."id";

alter sequence "horarios"."horario_general_id_seq" owned by "horarios"."horario_general"."id";

alter sequence "horarios"."horario_semanal_id_seq" owned by "horarios"."horario_semanal"."id";

alter sequence "horarios"."profesor_id_seq" owned by "horarios"."profesor"."id";

alter sequence "horarios"."turno_id_seq" owned by "horarios"."turno"."id";

CREATE UNIQUE INDEX careers_faculty_name_unique ON academico.careers USING btree (faculty_id, name);

CREATE UNIQUE INDEX careers_pkey ON academico.careers USING btree (id);

CREATE UNIQUE INDEX faculties_name_key ON academico.faculties USING btree (name);

CREATE UNIQUE INDEX faculties_pkey ON academico.faculties USING btree (id);

CREATE UNIQUE INDEX municipalities_name_key ON academico.municipalities USING btree (name);

CREATE UNIQUE INDEX municipalities_pkey ON academico.municipalities USING btree (id);

CREATE UNIQUE INDEX professors_pkey ON academico.professors USING btree (id);

CREATE UNIQUE INDEX professors_profile_id_key ON academico.professors USING btree (profile_id);

CREATE UNIQUE INDEX students_ci_key ON academico.students USING btree (ci);

CREATE UNIQUE INDEX students_pkey ON academico.students USING btree (id);

CREATE UNIQUE INDEX students_profile_id_key ON academico.students USING btree (profile_id);

CREATE UNIQUE INDEX asignatura_codigo_key ON horarios.asignatura USING btree (codigo);

CREATE UNIQUE INDEX asignatura_pkey ON horarios.asignatura USING btree (id);

CREATE UNIQUE INDEX horario_general_pkey ON horarios.horario_general USING btree (id);

CREATE UNIQUE INDEX horario_semanal_pkey ON horarios.horario_semanal USING btree (id);

CREATE INDEX idx_hs_asignatura ON horarios.horario_semanal USING btree (asignatura_id);

CREATE INDEX idx_hs_horario ON horarios.horario_semanal USING btree (horario_general_id);

CREATE INDEX idx_hs_profesor ON horarios.horario_semanal USING btree (profesor_id);

CREATE INDEX idx_hs_semana ON horarios.horario_semanal USING btree (semana_numero);

CREATE UNIQUE INDEX profesor_codigo_key ON horarios.profesor USING btree (codigo);

CREATE UNIQUE INDEX profesor_pkey ON horarios.profesor USING btree (id);

CREATE UNIQUE INDEX turno_pkey ON horarios.turno USING btree (id);

CREATE UNIQUE INDEX computers_pkey ON lab_services.computers USING btree (id);

CREATE UNIQUE INDEX computers_serial_number_key ON lab_services.computers USING btree (serial_number);

CREATE UNIQUE INDEX incidents_pkey ON lab_services.incidents USING btree (id);

CREATE UNIQUE INDEX labs_name_key ON lab_services.labs USING btree (name);

CREATE UNIQUE INDEX labs_pkey ON lab_services.labs USING btree (id);

CREATE UNIQUE INDEX agreement_pkey ON practicas.agreement USING btree (id);

CREATE UNIQUE INDEX company_pkey ON practicas.company USING btree (id);

CREATE UNIQUE INDEX company_profile_id_key ON practicas.company USING btree (profile_id);

CREATE UNIQUE INDEX prelocalization_assignment_call_student_unique ON practicas.prelocalization_assignment USING btree (prelocalization_call_id, student_id);

CREATE UNIQUE INDEX prelocalization_assignment_call_vacancy_unique ON practicas.prelocalization_assignment USING btree (prelocalization_call_id, vacancy_id);

CREATE UNIQUE INDEX prelocalization_assignment_pkey ON practicas.prelocalization_assignment USING btree (id);

CREATE UNIQUE INDEX prelocalization_call_pkey ON practicas.prelocalization_call USING btree (id);

CREATE UNIQUE INDEX prelocalization_ranking_call_position_unique ON practicas.prelocalization_ranking USING btree (prelocalization_call_id, "position");

CREATE UNIQUE INDEX prelocalization_ranking_call_student_unique ON practicas.prelocalization_ranking USING btree (prelocalization_call_id, student_id);

CREATE UNIQUE INDEX prelocalization_ranking_pkey ON practicas.prelocalization_ranking USING btree (id);

CREATE UNIQUE INDEX request_pkey ON practicas.request USING btree (id);

CREATE UNIQUE INDEX vacancy_pkey ON practicas.vacancy USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX roles_name_key ON public.roles USING btree (name);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

alter table "academico"."careers" add constraint "careers_pkey" PRIMARY KEY using index "careers_pkey";

alter table "academico"."faculties" add constraint "faculties_pkey" PRIMARY KEY using index "faculties_pkey";

alter table "academico"."municipalities" add constraint "municipalities_pkey" PRIMARY KEY using index "municipalities_pkey";

alter table "academico"."professors" add constraint "professors_pkey" PRIMARY KEY using index "professors_pkey";

alter table "academico"."students" add constraint "students_pkey" PRIMARY KEY using index "students_pkey";

alter table "horarios"."asignatura" add constraint "asignatura_pkey" PRIMARY KEY using index "asignatura_pkey";

alter table "horarios"."horario_general" add constraint "horario_general_pkey" PRIMARY KEY using index "horario_general_pkey";

alter table "horarios"."horario_semanal" add constraint "horario_semanal_pkey" PRIMARY KEY using index "horario_semanal_pkey";

alter table "horarios"."profesor" add constraint "profesor_pkey" PRIMARY KEY using index "profesor_pkey";

alter table "horarios"."turno" add constraint "turno_pkey" PRIMARY KEY using index "turno_pkey";

alter table "lab_services"."computers" add constraint "computers_pkey" PRIMARY KEY using index "computers_pkey";

alter table "lab_services"."incidents" add constraint "incidents_pkey" PRIMARY KEY using index "incidents_pkey";

alter table "lab_services"."labs" add constraint "labs_pkey" PRIMARY KEY using index "labs_pkey";

alter table "practicas"."agreement" add constraint "agreement_pkey" PRIMARY KEY using index "agreement_pkey";

alter table "practicas"."company" add constraint "company_pkey" PRIMARY KEY using index "company_pkey";

alter table "practicas"."prelocalization_assignment" add constraint "prelocalization_assignment_pkey" PRIMARY KEY using index "prelocalization_assignment_pkey";

alter table "practicas"."prelocalization_call" add constraint "prelocalization_call_pkey" PRIMARY KEY using index "prelocalization_call_pkey";

alter table "practicas"."prelocalization_ranking" add constraint "prelocalization_ranking_pkey" PRIMARY KEY using index "prelocalization_ranking_pkey";

alter table "practicas"."request" add constraint "request_pkey" PRIMARY KEY using index "request_pkey";

alter table "practicas"."vacancy" add constraint "vacancy_pkey" PRIMARY KEY using index "vacancy_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "academico"."careers" add constraint "careers_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES academico.faculties(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "academico"."careers" validate constraint "careers_faculty_id_fkey";

alter table "academico"."careers" add constraint "careers_faculty_name_unique" UNIQUE using index "careers_faculty_name_unique";

alter table "academico"."faculties" add constraint "faculties_name_key" UNIQUE using index "faculties_name_key";

alter table "academico"."municipalities" add constraint "municipalities_name_key" UNIQUE using index "municipalities_name_key";

alter table "academico"."professors" add constraint "professors_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "academico"."professors" validate constraint "professors_profile_id_fkey";

alter table "academico"."professors" add constraint "professors_profile_id_key" UNIQUE using index "professors_profile_id_key";

alter table "academico"."students" add constraint "students_career_id_fkey" FOREIGN KEY (career_id) REFERENCES academico.careers(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "academico"."students" validate constraint "students_career_id_fkey";

alter table "academico"."students" add constraint "students_ci_key" UNIQUE using index "students_ci_key";

alter table "academico"."students" add constraint "students_municipality_id_fkey" FOREIGN KEY (municipality_id) REFERENCES academico.municipalities(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "academico"."students" validate constraint "students_municipality_id_fkey";

alter table "academico"."students" add constraint "students_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "academico"."students" validate constraint "students_profile_id_fkey";

alter table "academico"."students" add constraint "students_profile_id_key" UNIQUE using index "students_profile_id_key";

alter table "academico"."students" add constraint "students_study_mode_check" CHECK ((study_mode = ANY (ARRAY['REGULAR_DIURNO'::text, 'CURSO_POR_ENCUENTRO'::text]))) not valid;

alter table "academico"."students" validate constraint "students_study_mode_check";

alter table "horarios"."asignatura" add constraint "asignatura_codigo_key" UNIQUE using index "asignatura_codigo_key";

alter table "horarios"."asignatura" add constraint "asignatura_profesor_id_fkey" FOREIGN KEY (profesor_id) REFERENCES horarios.profesor(id) not valid;

alter table "horarios"."asignatura" validate constraint "asignatura_profesor_id_fkey";

alter table "horarios"."horario_general" add constraint "horario_general_creado_por_fkey" FOREIGN KEY (creado_por) REFERENCES auth.users(id) not valid;

alter table "horarios"."horario_general" validate constraint "horario_general_creado_por_fkey";

alter table "horarios"."horario_semanal" add constraint "horario_semanal_asignatura_id_fkey" FOREIGN KEY (asignatura_id) REFERENCES horarios.asignatura(id) not valid;

alter table "horarios"."horario_semanal" validate constraint "horario_semanal_asignatura_id_fkey";

alter table "horarios"."horario_semanal" add constraint "horario_semanal_horario_general_id_fkey" FOREIGN KEY (horario_general_id) REFERENCES horarios.horario_general(id) ON DELETE CASCADE not valid;

alter table "horarios"."horario_semanal" validate constraint "horario_semanal_horario_general_id_fkey";

alter table "horarios"."horario_semanal" add constraint "horario_semanal_profesor_id_fkey" FOREIGN KEY (profesor_id) REFERENCES horarios.profesor(id) not valid;

alter table "horarios"."horario_semanal" validate constraint "horario_semanal_profesor_id_fkey";

alter table "horarios"."horario_semanal" add constraint "horario_semanal_turno_id_fkey" FOREIGN KEY (turno_id) REFERENCES horarios.turno(id) not valid;

alter table "horarios"."horario_semanal" validate constraint "horario_semanal_turno_id_fkey";

alter table "horarios"."profesor" add constraint "profesor_codigo_key" UNIQUE using index "profesor_codigo_key";

alter table "lab_services"."computers" add constraint "computers_lab_id_fkey" FOREIGN KEY (lab_id) REFERENCES lab_services.labs(id) ON DELETE CASCADE not valid;

alter table "lab_services"."computers" validate constraint "computers_lab_id_fkey";

alter table "lab_services"."computers" add constraint "computers_serial_number_key" UNIQUE using index "computers_serial_number_key";

alter table "lab_services"."incidents" add constraint "incidents_computer_id_fkey" FOREIGN KEY (computer_id) REFERENCES lab_services.computers(id) ON DELETE CASCADE not valid;

alter table "lab_services"."incidents" validate constraint "incidents_computer_id_fkey";

alter table "lab_services"."labs" add constraint "labs_name_key" UNIQUE using index "labs_name_key";

alter table "practicas"."agreement" add constraint "agreement_company_id_fkey" FOREIGN KEY (company_id) REFERENCES practicas.company(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "practicas"."agreement" validate constraint "agreement_company_id_fkey";

alter table "practicas"."company" add constraint "company_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."company" validate constraint "company_profile_id_fkey";

alter table "practicas"."company" add constraint "company_profile_id_key" UNIQUE using index "company_profile_id_key";

alter table "practicas"."prelocalization_assignment" add constraint "prelocalization_assignment_call_student_unique" UNIQUE using index "prelocalization_assignment_call_student_unique";

alter table "practicas"."prelocalization_assignment" add constraint "prelocalization_assignment_call_vacancy_unique" UNIQUE using index "prelocalization_assignment_call_vacancy_unique";

alter table "practicas"."prelocalization_assignment" add constraint "prelocalization_assignment_prelocalization_call_id_fkey" FOREIGN KEY (prelocalization_call_id) REFERENCES practicas.prelocalization_call(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."prelocalization_assignment" validate constraint "prelocalization_assignment_prelocalization_call_id_fkey";

alter table "practicas"."prelocalization_assignment" add constraint "prelocalization_assignment_vacancy_id_fkey" FOREIGN KEY (vacancy_id) REFERENCES practicas.vacancy(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."prelocalization_assignment" validate constraint "prelocalization_assignment_vacancy_id_fkey";

alter table "practicas"."prelocalization_call" add constraint "prelocalization_call_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "practicas"."prelocalization_call" validate constraint "prelocalization_call_created_by_fkey";

alter table "practicas"."prelocalization_ranking" add constraint "prelocalization_ranking_call_position_unique" UNIQUE using index "prelocalization_ranking_call_position_unique";

alter table "practicas"."prelocalization_ranking" add constraint "prelocalization_ranking_call_student_unique" UNIQUE using index "prelocalization_ranking_call_student_unique";

alter table "practicas"."prelocalization_ranking" add constraint "prelocalization_ranking_prelocalization_call_id_fkey" FOREIGN KEY (prelocalization_call_id) REFERENCES practicas.prelocalization_call(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."prelocalization_ranking" validate constraint "prelocalization_ranking_prelocalization_call_id_fkey";

alter table "practicas"."request" add constraint "request_vacancy_id_fkey" FOREIGN KEY (vacancy_id) REFERENCES practicas.vacancy(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."request" validate constraint "request_vacancy_id_fkey";

alter table "practicas"."vacancy" add constraint "vacancy_agreement_id_fkey" FOREIGN KEY (agreement_id) REFERENCES practicas.agreement(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "practicas"."vacancy" validate constraint "vacancy_agreement_id_fkey";

alter table "public"."profiles" add constraint "profiles_account_type_check" CHECK ((account_type = ANY (ARRAY['estudiante'::text, 'empresa'::text, 'admin'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_account_type_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."profiles" validate constraint "profiles_role_id_fkey";

alter table "public"."roles" add constraint "roles_name_key" UNIQUE using index "roles_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  selected_role_id bigint;
  selected_account_type text;
begin
  selected_account_type := lower(coalesce(new.raw_user_meta_data->>'account_type', 'estudiante'));

  if selected_account_type not in ('estudiante', 'empresa') then
    selected_account_type := 'estudiante';
  end if;

  select id
  into selected_role_id
  from public.roles
  where name = selected_account_type
  limit 1;

  if selected_role_id is null then
    raise exception 'No existe el rol para account_type %', selected_account_type;
  end if;

  insert into public.profiles (
    id,
    full_name,
    account_type,
    role_id
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    selected_account_type,
    selected_role_id
  );

  return new;
end;
$function$
;

grant delete on table "academico"."careers" to "anon";

grant insert on table "academico"."careers" to "anon";

grant select on table "academico"."careers" to "anon";

grant update on table "academico"."careers" to "anon";

grant delete on table "academico"."careers" to "authenticated";

grant insert on table "academico"."careers" to "authenticated";

grant select on table "academico"."careers" to "authenticated";

grant update on table "academico"."careers" to "authenticated";

grant delete on table "academico"."careers" to "service_role";

grant insert on table "academico"."careers" to "service_role";

grant select on table "academico"."careers" to "service_role";

grant update on table "academico"."careers" to "service_role";

grant delete on table "academico"."faculties" to "anon";

grant insert on table "academico"."faculties" to "anon";

grant select on table "academico"."faculties" to "anon";

grant update on table "academico"."faculties" to "anon";

grant delete on table "academico"."faculties" to "authenticated";

grant insert on table "academico"."faculties" to "authenticated";

grant select on table "academico"."faculties" to "authenticated";

grant update on table "academico"."faculties" to "authenticated";

grant delete on table "academico"."faculties" to "service_role";

grant insert on table "academico"."faculties" to "service_role";

grant select on table "academico"."faculties" to "service_role";

grant update on table "academico"."faculties" to "service_role";

grant delete on table "academico"."municipalities" to "anon";

grant insert on table "academico"."municipalities" to "anon";

grant select on table "academico"."municipalities" to "anon";

grant update on table "academico"."municipalities" to "anon";

grant delete on table "academico"."municipalities" to "authenticated";

grant insert on table "academico"."municipalities" to "authenticated";

grant select on table "academico"."municipalities" to "authenticated";

grant update on table "academico"."municipalities" to "authenticated";

grant delete on table "academico"."municipalities" to "service_role";

grant insert on table "academico"."municipalities" to "service_role";

grant select on table "academico"."municipalities" to "service_role";

grant update on table "academico"."municipalities" to "service_role";

grant delete on table "academico"."professors" to "anon";

grant insert on table "academico"."professors" to "anon";

grant select on table "academico"."professors" to "anon";

grant update on table "academico"."professors" to "anon";

grant delete on table "academico"."professors" to "authenticated";

grant insert on table "academico"."professors" to "authenticated";

grant select on table "academico"."professors" to "authenticated";

grant update on table "academico"."professors" to "authenticated";

grant delete on table "academico"."professors" to "service_role";

grant insert on table "academico"."professors" to "service_role";

grant select on table "academico"."professors" to "service_role";

grant update on table "academico"."professors" to "service_role";

grant delete on table "academico"."students" to "anon";

grant insert on table "academico"."students" to "anon";

grant select on table "academico"."students" to "anon";

grant update on table "academico"."students" to "anon";

grant delete on table "academico"."students" to "authenticated";

grant insert on table "academico"."students" to "authenticated";

grant select on table "academico"."students" to "authenticated";

grant update on table "academico"."students" to "authenticated";

grant delete on table "academico"."students" to "service_role";

grant insert on table "academico"."students" to "service_role";

grant select on table "academico"."students" to "service_role";

grant update on table "academico"."students" to "service_role";

grant delete on table "horarios"."asignatura" to "anon";

grant insert on table "horarios"."asignatura" to "anon";

grant references on table "horarios"."asignatura" to "anon";

grant select on table "horarios"."asignatura" to "anon";

grant trigger on table "horarios"."asignatura" to "anon";

grant truncate on table "horarios"."asignatura" to "anon";

grant update on table "horarios"."asignatura" to "anon";

grant delete on table "horarios"."asignatura" to "authenticated";

grant insert on table "horarios"."asignatura" to "authenticated";

grant references on table "horarios"."asignatura" to "authenticated";

grant select on table "horarios"."asignatura" to "authenticated";

grant trigger on table "horarios"."asignatura" to "authenticated";

grant truncate on table "horarios"."asignatura" to "authenticated";

grant update on table "horarios"."asignatura" to "authenticated";

grant delete on table "horarios"."asignatura" to "service_role";

grant insert on table "horarios"."asignatura" to "service_role";

grant references on table "horarios"."asignatura" to "service_role";

grant select on table "horarios"."asignatura" to "service_role";

grant trigger on table "horarios"."asignatura" to "service_role";

grant truncate on table "horarios"."asignatura" to "service_role";

grant update on table "horarios"."asignatura" to "service_role";

grant delete on table "horarios"."horario_general" to "anon";

grant insert on table "horarios"."horario_general" to "anon";

grant references on table "horarios"."horario_general" to "anon";

grant select on table "horarios"."horario_general" to "anon";

grant trigger on table "horarios"."horario_general" to "anon";

grant truncate on table "horarios"."horario_general" to "anon";

grant update on table "horarios"."horario_general" to "anon";

grant delete on table "horarios"."horario_general" to "authenticated";

grant insert on table "horarios"."horario_general" to "authenticated";

grant references on table "horarios"."horario_general" to "authenticated";

grant select on table "horarios"."horario_general" to "authenticated";

grant trigger on table "horarios"."horario_general" to "authenticated";

grant truncate on table "horarios"."horario_general" to "authenticated";

grant update on table "horarios"."horario_general" to "authenticated";

grant delete on table "horarios"."horario_general" to "service_role";

grant insert on table "horarios"."horario_general" to "service_role";

grant references on table "horarios"."horario_general" to "service_role";

grant select on table "horarios"."horario_general" to "service_role";

grant trigger on table "horarios"."horario_general" to "service_role";

grant truncate on table "horarios"."horario_general" to "service_role";

grant update on table "horarios"."horario_general" to "service_role";

grant delete on table "horarios"."horario_semanal" to "anon";

grant insert on table "horarios"."horario_semanal" to "anon";

grant references on table "horarios"."horario_semanal" to "anon";

grant select on table "horarios"."horario_semanal" to "anon";

grant trigger on table "horarios"."horario_semanal" to "anon";

grant truncate on table "horarios"."horario_semanal" to "anon";

grant update on table "horarios"."horario_semanal" to "anon";

grant delete on table "horarios"."horario_semanal" to "authenticated";

grant insert on table "horarios"."horario_semanal" to "authenticated";

grant references on table "horarios"."horario_semanal" to "authenticated";

grant select on table "horarios"."horario_semanal" to "authenticated";

grant trigger on table "horarios"."horario_semanal" to "authenticated";

grant truncate on table "horarios"."horario_semanal" to "authenticated";

grant update on table "horarios"."horario_semanal" to "authenticated";

grant delete on table "horarios"."horario_semanal" to "service_role";

grant insert on table "horarios"."horario_semanal" to "service_role";

grant references on table "horarios"."horario_semanal" to "service_role";

grant select on table "horarios"."horario_semanal" to "service_role";

grant trigger on table "horarios"."horario_semanal" to "service_role";

grant truncate on table "horarios"."horario_semanal" to "service_role";

grant update on table "horarios"."horario_semanal" to "service_role";

grant delete on table "horarios"."profesor" to "anon";

grant insert on table "horarios"."profesor" to "anon";

grant references on table "horarios"."profesor" to "anon";

grant select on table "horarios"."profesor" to "anon";

grant trigger on table "horarios"."profesor" to "anon";

grant truncate on table "horarios"."profesor" to "anon";

grant update on table "horarios"."profesor" to "anon";

grant delete on table "horarios"."profesor" to "authenticated";

grant insert on table "horarios"."profesor" to "authenticated";

grant references on table "horarios"."profesor" to "authenticated";

grant select on table "horarios"."profesor" to "authenticated";

grant trigger on table "horarios"."profesor" to "authenticated";

grant truncate on table "horarios"."profesor" to "authenticated";

grant update on table "horarios"."profesor" to "authenticated";

grant delete on table "horarios"."profesor" to "service_role";

grant insert on table "horarios"."profesor" to "service_role";

grant references on table "horarios"."profesor" to "service_role";

grant select on table "horarios"."profesor" to "service_role";

grant trigger on table "horarios"."profesor" to "service_role";

grant truncate on table "horarios"."profesor" to "service_role";

grant update on table "horarios"."profesor" to "service_role";

grant delete on table "horarios"."turno" to "anon";

grant insert on table "horarios"."turno" to "anon";

grant references on table "horarios"."turno" to "anon";

grant select on table "horarios"."turno" to "anon";

grant trigger on table "horarios"."turno" to "anon";

grant truncate on table "horarios"."turno" to "anon";

grant update on table "horarios"."turno" to "anon";

grant delete on table "horarios"."turno" to "authenticated";

grant insert on table "horarios"."turno" to "authenticated";

grant references on table "horarios"."turno" to "authenticated";

grant select on table "horarios"."turno" to "authenticated";

grant trigger on table "horarios"."turno" to "authenticated";

grant truncate on table "horarios"."turno" to "authenticated";

grant update on table "horarios"."turno" to "authenticated";

grant delete on table "horarios"."turno" to "service_role";

grant insert on table "horarios"."turno" to "service_role";

grant references on table "horarios"."turno" to "service_role";

grant select on table "horarios"."turno" to "service_role";

grant trigger on table "horarios"."turno" to "service_role";

grant truncate on table "horarios"."turno" to "service_role";

grant update on table "horarios"."turno" to "service_role";

grant delete on table "lab_services"."computers" to "anon";

grant insert on table "lab_services"."computers" to "anon";

grant references on table "lab_services"."computers" to "anon";

grant select on table "lab_services"."computers" to "anon";

grant trigger on table "lab_services"."computers" to "anon";

grant truncate on table "lab_services"."computers" to "anon";

grant update on table "lab_services"."computers" to "anon";

grant delete on table "lab_services"."computers" to "authenticated";

grant insert on table "lab_services"."computers" to "authenticated";

grant references on table "lab_services"."computers" to "authenticated";

grant select on table "lab_services"."computers" to "authenticated";

grant trigger on table "lab_services"."computers" to "authenticated";

grant truncate on table "lab_services"."computers" to "authenticated";

grant update on table "lab_services"."computers" to "authenticated";

grant delete on table "lab_services"."computers" to "service_role";

grant insert on table "lab_services"."computers" to "service_role";

grant references on table "lab_services"."computers" to "service_role";

grant select on table "lab_services"."computers" to "service_role";

grant trigger on table "lab_services"."computers" to "service_role";

grant truncate on table "lab_services"."computers" to "service_role";

grant update on table "lab_services"."computers" to "service_role";

grant delete on table "lab_services"."incidents" to "anon";

grant insert on table "lab_services"."incidents" to "anon";

grant references on table "lab_services"."incidents" to "anon";

grant select on table "lab_services"."incidents" to "anon";

grant trigger on table "lab_services"."incidents" to "anon";

grant truncate on table "lab_services"."incidents" to "anon";

grant update on table "lab_services"."incidents" to "anon";

grant delete on table "lab_services"."incidents" to "authenticated";

grant insert on table "lab_services"."incidents" to "authenticated";

grant references on table "lab_services"."incidents" to "authenticated";

grant select on table "lab_services"."incidents" to "authenticated";

grant trigger on table "lab_services"."incidents" to "authenticated";

grant truncate on table "lab_services"."incidents" to "authenticated";

grant update on table "lab_services"."incidents" to "authenticated";

grant delete on table "lab_services"."incidents" to "service_role";

grant insert on table "lab_services"."incidents" to "service_role";

grant references on table "lab_services"."incidents" to "service_role";

grant select on table "lab_services"."incidents" to "service_role";

grant trigger on table "lab_services"."incidents" to "service_role";

grant truncate on table "lab_services"."incidents" to "service_role";

grant update on table "lab_services"."incidents" to "service_role";

grant delete on table "lab_services"."labs" to "anon";

grant insert on table "lab_services"."labs" to "anon";

grant references on table "lab_services"."labs" to "anon";

grant select on table "lab_services"."labs" to "anon";

grant trigger on table "lab_services"."labs" to "anon";

grant truncate on table "lab_services"."labs" to "anon";

grant update on table "lab_services"."labs" to "anon";

grant delete on table "lab_services"."labs" to "authenticated";

grant insert on table "lab_services"."labs" to "authenticated";

grant references on table "lab_services"."labs" to "authenticated";

grant select on table "lab_services"."labs" to "authenticated";

grant trigger on table "lab_services"."labs" to "authenticated";

grant truncate on table "lab_services"."labs" to "authenticated";

grant update on table "lab_services"."labs" to "authenticated";

grant delete on table "lab_services"."labs" to "service_role";

grant insert on table "lab_services"."labs" to "service_role";

grant references on table "lab_services"."labs" to "service_role";

grant select on table "lab_services"."labs" to "service_role";

grant trigger on table "lab_services"."labs" to "service_role";

grant truncate on table "lab_services"."labs" to "service_role";

grant update on table "lab_services"."labs" to "service_role";

grant delete on table "practicas"."agreement" to "anon";

grant insert on table "practicas"."agreement" to "anon";

grant select on table "practicas"."agreement" to "anon";

grant update on table "practicas"."agreement" to "anon";

grant delete on table "practicas"."agreement" to "authenticated";

grant insert on table "practicas"."agreement" to "authenticated";

grant select on table "practicas"."agreement" to "authenticated";

grant update on table "practicas"."agreement" to "authenticated";

grant delete on table "practicas"."agreement" to "service_role";

grant insert on table "practicas"."agreement" to "service_role";

grant select on table "practicas"."agreement" to "service_role";

grant update on table "practicas"."agreement" to "service_role";

grant delete on table "practicas"."company" to "anon";

grant insert on table "practicas"."company" to "anon";

grant select on table "practicas"."company" to "anon";

grant update on table "practicas"."company" to "anon";

grant delete on table "practicas"."company" to "authenticated";

grant insert on table "practicas"."company" to "authenticated";

grant select on table "practicas"."company" to "authenticated";

grant update on table "practicas"."company" to "authenticated";

grant delete on table "practicas"."company" to "service_role";

grant insert on table "practicas"."company" to "service_role";

grant select on table "practicas"."company" to "service_role";

grant update on table "practicas"."company" to "service_role";

grant delete on table "practicas"."prelocalization_assignment" to "anon";

grant insert on table "practicas"."prelocalization_assignment" to "anon";

grant select on table "practicas"."prelocalization_assignment" to "anon";

grant update on table "practicas"."prelocalization_assignment" to "anon";

grant delete on table "practicas"."prelocalization_assignment" to "authenticated";

grant insert on table "practicas"."prelocalization_assignment" to "authenticated";

grant select on table "practicas"."prelocalization_assignment" to "authenticated";

grant update on table "practicas"."prelocalization_assignment" to "authenticated";

grant delete on table "practicas"."prelocalization_assignment" to "service_role";

grant insert on table "practicas"."prelocalization_assignment" to "service_role";

grant select on table "practicas"."prelocalization_assignment" to "service_role";

grant update on table "practicas"."prelocalization_assignment" to "service_role";

grant delete on table "practicas"."prelocalization_call" to "anon";

grant insert on table "practicas"."prelocalization_call" to "anon";

grant select on table "practicas"."prelocalization_call" to "anon";

grant update on table "practicas"."prelocalization_call" to "anon";

grant delete on table "practicas"."prelocalization_call" to "authenticated";

grant insert on table "practicas"."prelocalization_call" to "authenticated";

grant select on table "practicas"."prelocalization_call" to "authenticated";

grant update on table "practicas"."prelocalization_call" to "authenticated";

grant delete on table "practicas"."prelocalization_call" to "service_role";

grant insert on table "practicas"."prelocalization_call" to "service_role";

grant select on table "practicas"."prelocalization_call" to "service_role";

grant update on table "practicas"."prelocalization_call" to "service_role";

grant delete on table "practicas"."prelocalization_ranking" to "anon";

grant insert on table "practicas"."prelocalization_ranking" to "anon";

grant select on table "practicas"."prelocalization_ranking" to "anon";

grant update on table "practicas"."prelocalization_ranking" to "anon";

grant delete on table "practicas"."prelocalization_ranking" to "authenticated";

grant insert on table "practicas"."prelocalization_ranking" to "authenticated";

grant select on table "practicas"."prelocalization_ranking" to "authenticated";

grant update on table "practicas"."prelocalization_ranking" to "authenticated";

grant delete on table "practicas"."prelocalization_ranking" to "service_role";

grant insert on table "practicas"."prelocalization_ranking" to "service_role";

grant select on table "practicas"."prelocalization_ranking" to "service_role";

grant update on table "practicas"."prelocalization_ranking" to "service_role";

grant delete on table "practicas"."request" to "anon";

grant insert on table "practicas"."request" to "anon";

grant select on table "practicas"."request" to "anon";

grant update on table "practicas"."request" to "anon";

grant delete on table "practicas"."request" to "authenticated";

grant insert on table "practicas"."request" to "authenticated";

grant select on table "practicas"."request" to "authenticated";

grant update on table "practicas"."request" to "authenticated";

grant delete on table "practicas"."request" to "service_role";

grant insert on table "practicas"."request" to "service_role";

grant select on table "practicas"."request" to "service_role";

grant update on table "practicas"."request" to "service_role";

grant delete on table "practicas"."vacancy" to "anon";

grant insert on table "practicas"."vacancy" to "anon";

grant select on table "practicas"."vacancy" to "anon";

grant update on table "practicas"."vacancy" to "anon";

grant delete on table "practicas"."vacancy" to "authenticated";

grant insert on table "practicas"."vacancy" to "authenticated";

grant select on table "practicas"."vacancy" to "authenticated";

grant update on table "practicas"."vacancy" to "authenticated";

grant delete on table "practicas"."vacancy" to "service_role";

grant insert on table "practicas"."vacancy" to "service_role";

grant select on table "practicas"."vacancy" to "service_role";

grant update on table "practicas"."vacancy" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";


  create policy "allow_all"
  on "horarios"."asignatura"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."horario_general"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."horario_semanal"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."profesor"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "allow_all"
  on "horarios"."turno"
  as permissive
  for all
  to anon, authenticated
using (true)
with check (true);



  create policy "admin_computers_all"
  on "lab_services"."computers"
  as permissive
  for all
  to authenticated
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'lab_admin'::text));



  create policy "technician_read_own_computers"
  on "lab_services"."computers"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM lab_services.labs
  WHERE ((labs.id = computers.lab_id) AND (labs.technician_id = auth.uid())))));



  create policy "admin_incidents_all"
  on "lab_services"."incidents"
  as permissive
  for all
  to authenticated
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'lab_admin'::text));



  create policy "technician_incident_control"
  on "lab_services"."incidents"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (lab_services.computers
     JOIN lab_services.labs ON ((labs.id = computers.lab_id)))
  WHERE ((computers.id = incidents.computer_id) AND (labs.technician_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM (lab_services.computers
     JOIN lab_services.labs ON ((labs.id = computers.lab_id)))
  WHERE ((computers.id = incidents.computer_id) AND (labs.technician_id = auth.uid())))));



  create policy "admin_labs_all"
  on "lab_services"."labs"
  as permissive
  for all
  to authenticated
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'lab_admin'::text));



  create policy "technician_read_own_labs"
  on "lab_services"."labs"
  as permissive
  for select
  to authenticated
using ((technician_id = auth.uid()));



  create policy "Users can read their own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));



  create policy "Users can update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id));



  create policy "allow_read_profiles"
  on "public"."profiles"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "Authenticated users can read roles"
  on "public"."roles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "allow_read_roles"
  on "public"."roles"
  as permissive
  for select
  to anon, authenticated
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


